support for vectors in macro defines (ie: "name:='a b c'")
gkjohnson/xacro-parser pull request #52
Opened 2021-03-02 08:41 UTC by outchy

support for vectors in macro defines (ie: "name:='a b c'")

2021-04-20 18:16 UTC, gkjohnson requested changes
Thanks for the contribution! A couple changes but overall it looks good. Would you be able to add a test or two for this feature, as well?

2021-04-20 18:16 UTC, gkjohnson commented on src/XacroParser.js
> +                    obj.def = def.substr(1, def.length - 2);
Can we use "substring" here, instead. "substr" is listed as legacy in the [mdn docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring#the_difference_between_substring_and_substr).

2021-04-20 18:16 UTC, gkjohnson commented on src/XacroParser.js
> +                    .match(/[^\s']+(['][^']*['])?/g)
Do the single quotes need to be in brackets `[']`?

2021-04-23 22:00 UTC, gkjohnson commented
I'm about to make a new release so I'll make some of the remaining changes. Thanks again for the fix and contribution!

2021-04-23 22:00 UTC, merged

2021-04-27 10:32 UTC, outchy commented
Hello,

Apparently, everything is fine with your changes.

Thank you and sorry for the delay.

Cheers,

- Florent Ouchet

Le 24/04/2021 à 00:01, Garrett Johnson a écrit :
>
> Merged #52 <https://github.com/gkjohnson/xacro-parser/pull/52> into 
> master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/gkjohnson/xacro-parser/pull/52#event-4639011764>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AAY7AN4CWJ4ZU2WITXJ6AFTTKHU2XANCNFSM4YOONCNA>.
>